# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Mercury

on:
  # Runs on pushes targeting the default branch
  push:
    
    paths-ignore:
    - .github/**
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: Mercury Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Install OpenConnect
        run: |
          sudo apt-get update
          sudo apt-get install -y openconnect

      - name: Start VPN Connection
        run: |
          echo "${{ secrets.VPN_PASSWD }}" | sudo openconnect \
            --protocol=anyconnect \
            -u "${{ secrets.VPN_USER }}" \
            --passwd-on-stdin \
            --background \
            "${{ secrets.VPN_HOSTNAME }}" \
            --form-entry=main:secondary="push"
      - name: Deploy via SCP
        run: |
          scp -r ./* ${{ secrets.USERNAME }}@${{ vars.MERCURY_URI }}:~/${{ secrets.SITE_ROOT }}
        shell: bash
      # - name: Deploy via SCP
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ vars.MERCURY_URI }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: 22
      #     source: "./*" # Selects all files in your repository root
      #     target: "~/${{ secrets.SITE_ROOT }}" # The web root folder on your target server
      #     strip_components: 0
